import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fluent Futures - Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <div className="flex">
        <div className="w-[18%] border-r fixed top-0 left-0 overflow-y-auto">
          <Sidebar />
        </div>
        <div className="flex-1 ml-[20%]">
          {children}
        </div>
      </div>
    </body>
  </html>
  );
}
